set_property SRC_FILE_INFO {cfile:{C:/Users/ros3142/Desktop/RTL Projects/ES100_Mitchell_Sharum/ES100_Mitchell_Sharum.srcs/constrs_1/new/constraints.xdc} rfile:../../../ES100_Mitchell_Sharum.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB2 [get_ports o_codec_mclock]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA6 [get_ports i_codec_bit_clock]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y6 [get_ports i_codec_lr_clock]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports o_codec_dac_data]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA7 [get_ports i_codec_adc_data]
